'use client'
import GlobalStyle from "@/assets/globalStyle"
import SideBar from "@/components/SideBar";
import { usePathname } from "next/navigation";

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const pathName = usePathname()

  return (
    <html lang="en">
      <GlobalStyle/>
      <body >
        {pathName !== '/login' && <SideBar/>  }
        {children}
        </body>
    </html>
  )
}
